/**
 * Sidebar configuration for Support Knowledge Base
 */

module.exports = {
  knowledgeBaseSidebar: [
    {
      type: 'doc',
      id: 'index',
      label: 'Knowledge Base Home',
    },
    {
      type: 'category',
      label: 'Products',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'access-analyzer',
        },
        {
          type: 'autogenerated',
          dirName: 'activity-monitor',
        },
        {
          type: 'autogenerated',
          dirName: 'auditor',
        },
        {
          type: 'autogenerated',
          dirName: 'change-tracker',
        },
        {
          type: 'autogenerated',
          dirName: 'data-classification',
        },
        {
          type: 'autogenerated',
          dirName: 'directory-manager',
        },
        {
          type: 'autogenerated',
          dirName: 'endpoint-policy-manager',
        },
        {
          type: 'autogenerated',
          dirName: 'endpoint-protector',
        },
        {
          type: 'autogenerated',
          dirName: 'log-tracker',
        },
        {
          type: 'autogenerated',
          dirName: 'onesecure',
        },
        {
          type: 'autogenerated',
          dirName: 'password-policy-enforcer',
        },
        {
          type: 'autogenerated',
          dirName: 'password-reset',
        },
        {
          type: 'autogenerated',
          dirName: 'privilege-secure-access-management',
        },
        {
          type: 'autogenerated',
          dirName: 'privilege-secure-discovery',
        },
        {
          type: 'autogenerated',
          dirName: 'recovery-active-directory',
        },
        {
          type: 'autogenerated',
          dirName: 'threat-manager',
        },
        {
          type: 'autogenerated',
          dirName: 'threat-prevention',
        },
        {
          type: 'autogenerated',
          dirName: 'vulnerability-tracker',
        },
      ],
    },
    {
      type: 'category',
      label: 'General',
      items: [
        {
          type: 'autogenerated',
          dirName: 'general',
        },
      ],
    },
  ],
};